#!/bin/bash

cd "$(git rev-parse --show-toplevel)"

build() {
	echo "🔨 Building the project ..."

	output=$(go build . 2>&1)
	exit_code=$?

	if [ $exit_code -ne 0 ]; then
		echo "❌ Build failed:" >&2
		echo "$output" >&2
		exit $exit_code
	fi

	echo "✅ Build succeeded."
}

lint() {
	echo "🔍 Linting the project ..."

	if command -v golangci-lint &> /dev/null; then
		cilint
	else
		echo "⚠️ golangci-lint not found, falling back to go vet." >&2
		vet
	fi
}

cilint() {
	output=$(golangci-lint run 2>&1)
	exit_code=$?

	if [ $exit_code -ne 0 ]; then
		echo "❌ Linting failed:" >&2
		echo "$output" >&2
		exit $exit_code
	fi

	echo "✅ Linting passed."
}

vet() {
	output=$((go list ./... | rg -v "codeberg.org/BelWue/flowpipeline/pb" | xargs -r go vet) 2>&1)
	# Exclude dropfields, as tests are annotated with nolint and go vet does not respect that
	output=$(
		go list ./... \
		| rg -v "codeberg.org/BelWue/flowpipeline/pb" \
		| rg -v "codeberg.org/BelWue/flowpipeline/segments/modify/dropfields" \
		| xargs -r -n1 go vet
	) 2>&1
	exit_code=$?

	if [ $exit_code -ne 0 ]; then
		echo "❌ Linting failed:" >&2
		echo "$output" >&2
		exit $exit_code
	fi

	echo "✅ Vetting passed."
}

build
echo ""
lint
