#!/bin/bash

cd "$(git rev-parse --show-toplevel)"

echo "🔨 Building the project ..."

output=$(go build . 2>&1)
exit_code=$?

if [ $exit_code -ne 0 ]; then
	echo "❌ Build failed:" >&2
	echo "$output" >&2
	exit $exit_code
else
	echo "✅ Build succeeded."
	exit 0
fi
