version: "2"
formatters:
  enable:
    - gofmt
linters:
  enable:
    - decorder
    - embeddedstructfieldcheck
    - exhaustive
  settings:
    copyloopvar:
      check-alias: true
    embeddedstructfieldcheck:
      empty-line: false
