version: "2"
output:
  formats:
    tab:
      path: stdout
formatters:
  enable:
    - gofmt
linters:
  enable:
    - decorder
    - embeddedstructfieldcheck
    - exhaustive
  disable:
    - errcheck
  exclusions:
    rules:
      - linters:
        - embeddedstructfieldcheck
        text: "there must be an empty line separating embedded fields from regular fields"
    paths:
      - pb/
  settings:
    copyloopvar:
      check-alias: true
    embeddedstructfieldcheck:
      empty-line: false
    exhaustive:
      default-signifies-exhaustive: true
