name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    permissions:
      contents: read
      checks: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: BelWü
          goos: linux
        #- os: macos-latest
          #goos: darwin
    steps:
    - name: Checkout
      uses: https://code.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Install libpcap-dev
      if: matrix.goos == 'linux'
      run: apt-get update && apt-get install -y libpcap-dev

    - name: Setup go
      uses: https://code.forgejo.org/actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        go-version-file: 'go.mod'
        cache: ${{ vars.CACHING }}

    - name: Run go tests
      run: go test ./...

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: BelWü
          goos: linux
        #- os: macos-latest
          #goos: darwin
    steps:
    - name: Checkout
      uses: https://code.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Install libpcap-dev
      if: matrix.goos == 'linux'
      run: apt-get update && apt-get install -y libpcap-dev

    - name: Setup go
      uses: https://code.forgejo.org/actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        go-version-file: 'go.mod'
        cache: ${{ vars.CACHING }}

    - name: Build dynamically linked
      run: go build -o flowpipeline -ldflags "-X main.Version=${{ forge.sha }}" .

    - name: Save dynamically linked binary
      uses: https://code.forgejo.org/forgejo/upload-artifact/@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
      with:
        name: flowpipeline-${{ matrix.goos }}
        path: ./flowpipeline
        overwrite: true

    - name: Build statically linked
      run: go build -o flowpipeline-static -ldflags "-X main.Version=${{ forge.sha }}" .
      env:
        CGO_ENABLED: 0

    - name: Save statically linked binary
      uses: https://code.forgejo.org/forgejo/upload-artifact/@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
      with:
        name: flowpipeline-${{ matrix.goos }}-static
        path: ./flowpipeline-static
        overwrite: true
