name: Containers

on:
  workflow_dispatch:
  release:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
    paths:
      - .forgejo/**
      - Containerfile
      - examples/visualization/**

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: codeberg.org
  IMAGE_NAME: ${{ forge.repository }}
  IMAGE_NAME_VISUALIZATION: ${{ forge.repository }}-grafana


jobs:
  extract-container-labels:

    runs-on: BelWü
    permissions:
      contents: read
    outputs:
      flowpipeline-tags: ${{ steps.meta-flowpipeline.outputs.tags }}
      visualization-tags: ${{ steps.meta-visualization.outputs.tags }}

    steps:
      # Extract metadata (tags, labels) for Container
      - name: Extract flowpipeline container metadata
        id: meta-flowpipeline
        uses: https://code.forgejo.org/docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=${{ startsWith(forge.ref, 'refs/tags/') && ! contains(forge.ref, '-alpha') && ! contains(forge.ref, '-beta') }}

      # Extract metadata (tags, labels) for visualization container
      - name: Extract visualization container metadata
        id: meta-visualization
        uses: https://code.forgejo.org/docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_VISUALIZATION }}
          flavor: latest=${{ startsWith(forge.ref, 'refs/tags/') && ! contains(forge.ref, '-alpha') && ! contains(forge.ref, '-beta') }}

  flowpipeline:

    needs:
      - extract-container-labels
    runs-on: BelWü
    container:
      image: docker.io/martizih/kaniko:v1.26.1-debug@sha256:6a01e35fc43218b104cebaa63e1a41c811db7c69a5dcf37b80537ff41a2d08de
    permissions:
      contents: read
      packages: write

    steps:
      # Build and push container image with Kaniko (don't push on PR)
      - name: Build and push container image
        run: |
          # Write authentication data in config file
          AUTH=$(echo -n ${{ forge.repository_owner }}:${{ secrets.CODEBERG_PACKAGE_REPOSITORY_TOKEN }} | base64 -w0)
          echo "{\"auths\": {\"${{ env.REGISTRY }}\": {\"auth\": \"${AUTH}\"}}}" > /kaniko/.docker/config.json

          # Configure git for pull
          export GIT_USERNAME="git"
          export GIT_PASSWORD="${{ secrets.FORGEJO_TOKEN }}"

          # Create Kaniko cmdline
          set -- /kaniko/executor --dockerfile="./Containerfile" --context="git://${{ env.REGISTRY }}/${{ forge.repository }}#${{ forge.ref }}#${{ forge.sha }}" --compressed-caching=false --reproducible

          while IFS= read -r destination; do
            set -- "$@" --destination "$destination"
          done <<END
          ${{ needs.extract-container-labels.outputs.flowpipeline-tags }}
          END

          if ${{ forge.event_name == 'pull_request' }}; then
            set -- "$@" --no-push
          fi

          echo "$@"

          # Build and push image
          exec "$@"

  visualization:

    needs:
      - extract-container-labels
      - flowpipeline
    runs-on: BelWü
    container:
      image: docker.io/martizih/kaniko:v1.26.1-debug@sha256:6a01e35fc43218b104cebaa63e1a41c811db7c69a5dcf37b80537ff41a2d08de
    permissions:
      contents: read
      packages: write

    steps:
      # Build and push container image with Kaniko (don't push on PR)
      - name: Build and push container image
        run: |
          # Write authentication data in config file
          AUTH=$(echo -n ${{ forge.repository_owner }}:${{ secrets.CODEBERG_PACKAGE_REPOSITORY_TOKEN }} | base64 -w0)
          echo "{\"auths\": {\"${{ env.REGISTRY }}\": {\"auth\": \"${AUTH}\"}}}" > /kaniko/.docker/config.json

          # Configure git for pull
          export GIT_USERNAME="git"
          export GIT_PASSWORD="${{ secrets.FORGEJO_TOKEN }}"

          # Create Kaniko cmdline
          set -- /kaniko/executor --dockerfile="./examples/visualization/Containerfile" --context="git://${{ env.REGISTRY }}/${{ forge.repository }}#${{ forge.ref }}#${{ forge.sha }}" --compressed-caching=false --reproducible

          while IFS= read -r destination; do
            set -- "$@" --destination "$destination"
          done <<END
          ${{ needs.extract-container-labels.outputs.visualization-tags }}
          END

          if ${{ forge.event_name == 'pull_request' }}; then
            set -- "$@" --no-push
          fi

          echo "$@"

          # Build and push image
          exec "$@"
