name: Check for dependency updates

on:
  workflow_dispatch: # For manual triggers
  schedule: # To regularly get new updates even without activity
    - cron: '47 14 * * */7' # Every seven days at a random daytime
  pull_request_target: # Needed so RENOVATE_TOKEN is available
    types: [reopened, closed, synchronize, edited] # So Renovate can directly react to merged/closed/modified PRs

env:
  CACHE_DIR: /tmp/renovate-cache
  CACHE_KEY: renovate-cache

jobs:
  renovate:
    if: ${{ forge.actor }} != 'flowpipeline-bot' # Prevent potential trigger loops
    runs-on: BelWü
    container:
      image: docker.io/renovate/renovate:41@sha256:e998e1218fe572e23278d8808186a310784f7cb2ac8055307183ffc51d3a59e5
    steps:
      - name: Restore Renovate cache
        uses: https://code.forgejo.org/actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_DIR }}

      - name: Run Renovate
        run: renovate
        env:
          # With this, we can set global config options in the same file.
          # https://docs.renovatebot.com/config-overview/#global-config
          RENOVATE_REPOSITORY_CACHE: true
          RENOVATE_CACHE_DIR: ${{ env.CACHE_DIR }}
          RENOVATE_PLATFORM: forgejo
          RENOVATE_ENDPOINT: ${{ forge.api_url }}
          RENOVATE_REPOSITORIES: ${{ forge.repository }}
          RENOVATE_ONBOARDING_CONFIG_FILE_NAME: .renovaterc.json
          RENOVATE_GIT_AUTHOR: 'Flowpipeline Bot <flowpipeline-bot@noreply.codeberg.org>'
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}

      - name: Save Renovate cache
        uses: https://code.forgejo.org/actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_DIR }}
