name: Generate the configuration markdown file

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  CONFIG_FILE: "Configuration.md"
  GENERATOR_EXEC: "./generator"

jobs:
  build-and-commit:
    permissions:
      contents: write
    if: forge.event.pull_request.merged == true
    runs-on: BelWü
    steps:
      - name: Checkout Code
        uses: https://code.forgejo.org/actions/checkout@v5
        with:
          repository: BelWue/flowpipeline
          path: flowpipeline

      - name: Checkout Wiki
        uses: https://code.forgejo.org/actions/checkout@v5
        with:
          repository: BelWue/flowpipeline.wiki
          path: wiki
          ref: main

      - name: Set up Go
        uses: https://code.forgejo.org/actions/setup-go@v6
        with:
          go-version-file: 'flowpipeline/go.mod'

      - name: Build config generator
        working-directory: flowpipeline
        run: go build -o $GENERATOR_EXEC ./meta/doc_generator

      - name: Generate configuration markdown file
        working-directory: flowpipeline
        run: $GENERATOR_EXEC -out "$CONFIG_FILE"

      - name: Commit and Push Changes
        working-directory: wiki
        run: |
          git config --global user.name "codeberg-actions[bot]"
          git config --global user.email "codeberg-actions[bot]@users.noreply.codeberg.org"

          cp ../flowpipeline/$CONFIG_FILE .

          git add "$CONFIG_FILE"

          if ! git diff --staged --quiet; then
            git commit -m "docs: auto-generated $CONFIG_FILE"
            git push origin main
          else
            echo "No changes to commit."
          fi
