name: Linting

on:
  pull_request:

jobs:
  lint-go:
    permissions:
      contents: read
    runs-on: BelWü
    steps:
    - name: checkout
      uses: https://code.forgejo.org/actions/checkout@v5

    - name: setup go
      id: setup-go
      uses: https://code.forgejo.org/actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: install libpcap
      if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
      run: apt-get update && apt-get install -y libpcap-dev

    - name: golangci-lint
      uses: https://github.com/golangci/golangci-lint-action@v8
      with:
        version: latest
        skip-cache: true
