name: Linting

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  lint-go:
    permissions:
      contents: read
    runs-on: BelWü
    steps:
      - name: Checkout repo
        uses: https://code.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup go
        id: setup-go
        uses: https://code.forgejo.org/actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: 'go.mod'
          cache: ${{ vars.CACHING }}

      - name: Install libpcap-dev
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        run: apt-get update && apt-get install -y libpcap-dev

      - name: Run golangci-lint
        uses: https://github.com/golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47 # v9
        with:
          version: latest
          skip-cache: true

  lint-commits:
    runs-on: BelWü
    container:
      image: docker.io/commitlint/commitlint:20.1.0@sha256:caf971bc6ab2744d20f9967df648f210d6e79dda4055748d183d31700986f115
    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Validate PR commits with commitlint
        run: commitlint --config .forgejo/workflows/.commitlintrc.json --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
