name: release version tag

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  build:
    permissions:
      contents: read
      checks: write
      attestations: write 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: codeberg-small
          goos: linux
        #- os: macos-latest
          #goos: darwin
    steps:
    - name: checkout
      uses: https://code.forgejo.org/actions/checkout@v5

    - name: install libpcap
      if: matrix.goos == 'linux'
      run: sudo apt-get update && sudo apt-get install -y libpcap-dev

    - name: setup go
      uses: https://code.forgejo.org/actions/setup-go@v5
      with:
        go-version: '1.24.0'

    - name: test before release
      run: go test ./...

    - name: build binary
      run: go build -o flowpipeline-${{ matrix.goos }} -ldflags "-X main.Version=${{ forge.ref_name }}" .

    - name: build statically linked
      run: go build -o flowpipeline-${{ matrix.goos }}-static -ldflags "-X main.Version=${{ forge.ref_name }}" .
      env:
        CGO_ENABLED: 0

    - name: save statically linked binary
      uses: https://code.forgejo.org/forgejo/upload-artifact/@v4
      with:
        name: flowpipeline-${{ matrix.goos }}
        path: ./flowpipeline-*
        overwrite: true


  release:
    permissions:
      attestations: read 
      contents: write
    runs-on: codeberg-small
    needs: build
    steps:
    - name: setup go
      uses: https://code.forgejo.org/actions/setup-go@v5
      with:
        go-version: '1.24.0'
    - name: get binaries from previous job
      uses: https://code.forgejo.org/forgejo/download-artifact/@v4
    - name: display downloaded files
      run: ls -R
    - name: release with binaries
      uses: https://github.com/softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        prerelease: ${{ endsWith(forge.ref, '-alpha') || endsWith(forge.ref, '-beta') }}
        files: "flowpipeline-*/flowpipeline-*"
