name: Release

on:
  push:
    tags: [ "v*.*.*" ]
  workflow_dispatch: # For manual triggers

jobs:
  build:
    permissions:
      contents: read
      checks: write
      attestations: write 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: BelWü
          goos: linux
        #- os: macos-latest
          #goos: darwin
    steps:
    - name: Checkout repo
      uses: https://code.forgejo.org/actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

    - name: Install libpcap-dev
      if: matrix.goos == 'linux'
      run: apt-get update && apt-get install -y libpcap-dev

    - name: Setup go
      uses: https://code.forgejo.org/actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Test before release
      run: go test ./...

    - name: Build dynamically linked binary
      run: go build -o flowpipeline-${{ matrix.goos }} -ldflags "-X main.Version=${{ forge.ref_name }}" .

    - name: Build statically linked binary
      run: go build -o flowpipeline-${{ matrix.goos }}-static -ldflags "-X main.Version=${{ forge.ref_name }}" .
      env:
        CGO_ENABLED: 0

    - name: Save binaries
      uses: https://code.forgejo.org/forgejo/upload-artifact/@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
      with:
        name: flowpipeline-${{ matrix.goos }}
        path: ./flowpipeline-*
        overwrite: true


  release:
    permissions:
      attestations: read 
      contents: write
    runs-on: BelWü
    needs: build
    steps:
    - name: Get binaries from previous job
      uses: https://code.forgejo.org/forgejo/download-artifact/@d8d0a99033603453ad2255e58720b460a0555e1e # v4

    - name: Display downloaded files
      run: ls -R

    - name: Release with binaries
      uses: https://github.com/softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2
      with:
        generate_release_notes: true
        prerelease: ${{ contains(forge.ref, '-alpha') || contains(forge.ref, '-beta') }}
        files: "flowpipeline-*/flowpipeline-*"
