# use official prometheus container image
FROM quay.io/prometheus/prometheus:v3.7.3@sha256:49214755b6153f90a597adcbff0252cc61069f8ab69ce8411285cd4a560e8038 AS prometheus

# use official grafana container image
FROM docker.io/grafana/grafana:12.2.1@sha256:35c41e0fd0295f5d0ee5db7e780cf33506abfaf47686196f825364889dee878b AS grafana

# begin new container based on the standalone flowpipeline one
FROM codeberg.org/belwue/flowpipeline:latest

RUN apk add --no-cache supervisor

WORKDIR /flowpipeline-example

COPY --from=prometheus /bin/prometheus .
#COPY --from=prometheus /opt/build/prometheus/web/ui/static static

COPY --from=grafana /usr/share/grafana/ /usr/share/grafana/
COPY --from=grafana /etc/grafana/ /etc/grafana/

# add configuration files for all services
COPY examples/visualization/flowpipeline/flowpipeline-config.yml config/flowpipeline-config.yml

COPY examples/visualization/prometheus/prometheus-config.yml config/prometheus-config.yml

# add example grafana dashboards
COPY examples/visualization/grafana/grafana-datasource.yaml /usr/share/grafana/conf/provisioning/datasources/default.yml
COPY examples/visualization/grafana/grafana-dashboards.yaml /usr/share/grafana/conf/provisioning/dashboards/default.yml

COPY examples/visualization/grafana/dashboards/overview.json ./dashboards/overview.json
COPY examples/visualization/grafana/dashboards/raw-data.json ./dashboards/raw-data.json

# Create supervisord configuration
COPY examples/visualization/supervisord.conf /etc/supervisor/supervisord.conf

# Start grafana, prometheus & flowpipeline 
ENTRYPOINT ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
