{
 "title": "Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Addresses",
    "label": "Addresses",
    "query": {
     "query": "label_values(traffic_bps,address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Traffic bps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(traffic_bps)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Traffic bps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(traffic_pps)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic bps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "traffic_bps{address=~\"$Addresses\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic pps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "traffic_pps{address=~\"$Addresses\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic by destination port",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "all_flow_bits{SrcAddr=~\"$Addresses\"} or all_flow_bits{DstAddr=~\"$Addresses\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic by Src Port",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "all_flow_bits{SrcAddr=~\"$Addresses\"} or all_flow_bits{DstAddr=~\"$Addresses\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic by Proto",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "all_flow_bits{SrcAddr=~\"$Addresses\"} or all_flow_bits{DstAddr=~\"$Addresses\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtered Flows",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "all_flow_bits{SrcAddr=~\"$Addresses\"} or all_flow_bits{DstAddr=~\"$Addresses\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}